#!/bin/bash

# Pre-commit hook to run quality checks
# This hook runs automatically before each commit
# It calls the centralized pre-commit checks script

# Run the pre-commit checks script
./scripts/pre-commit-checks.sh

# Exit with the same code as the checks script
exit $?

