.PHONY: help gen-proto gen-proto-go gen-proto-java gen-proto-ts verify-proto \
        build build-hello build-todo build-web \
        test test-hello test-todo test-web \
        docker-build docker-build-hello docker-build-todo \
        dev clean

# Default target
help:
	@echo "Monorepo Build System"
	@echo ""
	@echo "Available targets:"
	@echo "  gen-proto          - Generate code from Protobuf definitions (all languages)"
	@echo "  gen-proto-go       - Generate Go code from Protobuf"
	@echo "  gen-proto-java     - Generate Java code from Protobuf"
	@echo "  gen-proto-ts       - Generate TypeScript code from Protobuf"
	@echo "  verify-proto       - Verify generated code is up to date (for CI)"
	@echo ""
	@echo "  build              - Build all services"
	@echo "  build-hello        - Build Hello service (Java)"
	@echo "  build-todo         - Build TODO service (Go)"
	@echo "  build-web          - Build Web application (React)"
	@echo ""
	@echo "  test               - Run all tests"
	@echo "  test-hello         - Run Hello service tests"
	@echo "  test-todo          - Run TODO service tests"
	@echo "  test-web           - Run Web application tests"
	@echo ""
	@echo "  docker-build       - Build all Docker images"
	@echo "  docker-build-hello - Build Hello service Docker image"
	@echo "  docker-build-todo  - Build TODO service Docker image"
	@echo ""
	@echo "  dev                - Start all services in development mode"
	@echo "  clean              - Clean all build artifacts"

# Protobuf code generation
gen-proto: gen-proto-go gen-proto-java gen-proto-ts

gen-proto-go:
	@echo "Generating Go code from Protobuf..."
	@mkdir -p apps/todo-service/gen
	protoc --go_out=apps/todo-service/gen \
	       --go_opt=paths=source_relative \
	       --go-grpc_out=apps/todo-service/gen \
	       --go-grpc_opt=paths=source_relative \
	       -I api/v1 \
	       api/v1/*.proto

gen-proto-java:
	@echo "Generating Java code from Protobuf..."
	@echo "Note: Java code generation is typically handled by Maven/Gradle plugins."
	@echo "If you need to generate manually, ensure protoc-gen-grpc-java is installed."
	@mkdir -p apps/hello-service/src/main/java-gen
	@if command -v protoc-gen-grpc-java >/dev/null 2>&1; then \
		protoc --java_out=apps/hello-service/src/main/java-gen \
		       --grpc-java_out=apps/hello-service/src/main/java-gen \
		       -I api/v1 \
		       api/v1/hello.proto; \
	else \
		echo "Warning: protoc-gen-grpc-java not found. Java code will be generated by Maven/Gradle."; \
		echo "To install: Download from https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/"; \
	fi

gen-proto-ts:
	@echo "Generating TypeScript code from Protobuf..."
	@if [ -d "apps/web" ]; then \
		mkdir -p apps/web/src/gen; \
		cd apps/web && npm install; \
		protoc --plugin=./apps/web/node_modules/.bin/protoc-gen-ts_proto \
		       --ts_proto_out=apps/web/src/gen \
		       --ts_proto_opt=esModuleInterop=true \
		       --ts_proto_opt=outputServices=grpc-web \
		       -I api/v1 \
		       api/v1/*.proto; \
	else \
		echo "Warning: apps/web directory not found. Skipping TypeScript generation."; \
		echo "TypeScript code will be generated when the web app is initialized."; \
	fi

# CI verification
verify-proto:
	@echo "Verifying generated code is up to date..."
	@$(MAKE) gen-proto
	@git diff --exit-code apps/*/gen apps/*/src/main/java-gen apps/*/src/gen || \
	  (echo "Generated code is out of date. Run 'make gen-proto' and commit changes." && exit 1)

# Build targets
build: build-hello build-todo build-web

build-hello:
	@echo "Building Hello service..."
	@cd apps/hello-service && ./mvnw clean package -DskipTests

build-todo:
	@echo "Building TODO service..."
	@cd apps/todo-service && go build -o bin/todo-service .

build-web:
	@echo "Building Web application..."
	@cd apps/web && npm run build

# Test targets
test: test-hello test-todo test-web

test-hello:
	@echo "Running Hello service tests..."
	@cd apps/hello-service && ./mvnw test

test-todo:
	@echo "Running TODO service tests..."
	@cd apps/todo-service && go test ./...

test-web:
	@echo "Running Web application tests..."
	@cd apps/web && npm test

# Docker build targets
docker-build: docker-build-hello docker-build-todo

docker-build-hello:
	@echo "Building Hello service Docker image..."
	@docker build -t hello-service:latest apps/hello-service

docker-build-todo:
	@echo "Building TODO service Docker image..."
	@docker build -t todo-service:latest apps/todo-service

# Development mode
dev:
	@echo "Starting all services in development mode..."
	@./scripts/dev.sh

# Clean
clean:
	@echo "Cleaning build artifacts..."
	@rm -rf apps/hello-service/target
	@rm -rf apps/todo-service/bin
	@rm -rf apps/web/dist
	@rm -rf apps/web/node_modules/.vite
	@echo "Clean complete"
