.PHONY: help init check-env check-versions proto gen-proto gen-proto-go gen-proto-java gen-proto-ts verify-proto \
        build test lint lint-fix format docker-build run clean list-apps create \
        test-coverage test-coverage-hello test-coverage-todo verify-coverage verify-coverage-hello verify-coverage-todo \
        dev pre-commit

# Default target
help:
	@echo "Monorepo Build System"
	@echo ""
	@echo "Available targets:"
	@echo "  init               - Initialize development environment and install dependencies"
	@echo "  check-env          - Check if all required tools are installed"
	@echo "  check-versions     - Verify tool versions match requirements"
	@echo "  proto              - Generate code from Protobuf definitions (all languages)"
	@echo "  verify-proto       - Verify generated code is up to date (for CI)"
	@echo ""
	@echo "  Quality & Testing:"
	@echo "  pre-commit         - Run all pre-commit quality checks (lint, test, security)"
	@echo "  lint [APP=name]    - Run linters for app(s)"
	@echo "  lint-fix [APP=name] - Auto-fix lint errors for app(s)"
	@echo "  format [APP=name]  - Format code for app(s)"
	@echo "  test [APP=name]    - Run tests for app(s)"
	@echo "  test-coverage      - Run tests with coverage for all services"
	@echo ""
	@echo "  App Management (supports APP=<name> or auto-detects changed apps):"
	@echo "  list-apps          - List all available apps"
	@echo "  create             - Create a new app from template"
	@echo "  build [APP=name]   - Build app(s)"
	@echo "  docker-build [APP=name] - Build Docker image(s)"
	@echo "  run [APP=name]     - Run app(s) locally"
	@echo "  clean [APP=name]   - Clean build artifacts for app(s)"
	@echo ""
	@echo "  dev                - Start all services in development mode"
	@echo ""
	@echo "Examples:"
	@echo "  make pre-commit                # Run all quality checks before commit"
	@echo "  make proto                     # Generate code from Protobuf"
	@echo "  make test APP=hello            # Test specific app (short name)"
	@echo "  make lint-fix                  # Fix linting issues in all changed apps"
	@echo "  make build APP=todo            # Build specific app (short name)"

# Initialization
init:
	@echo "Initializing development environment..."
	@./scripts/init.sh

# Environment check
check-env:
	@./scripts/check-env.sh

# Version check
check-versions:
	@./scripts/check-versions.sh

# Protobuf code generation
proto: gen-proto-go gen-proto-java gen-proto-ts
	@echo "✅ Protobuf code generation completed for all languages"

# Legacy alias for backward compatibility
gen-proto: proto
	@echo "Note: 'gen-proto' is deprecated. Use 'make proto' instead."

# Convenience aliases for CI (without gen- prefix)
proto-go: gen-proto-go
proto-java: gen-proto-java
proto-ts: gen-proto-ts

gen-proto-go:
	@echo "Generating Go code from Protobuf..."
	@mkdir -p apps/todo-service/gen/hellopb
	@mkdir -p apps/todo-service/gen/todopb
	protoc --go_out=apps/todo-service/gen/hellopb \
	       --go_opt=paths=source_relative \
	       --go-grpc_out=apps/todo-service/gen/hellopb \
	       --go-grpc_opt=paths=source_relative \
	       -I api/v1 \
	       api/v1/hello.proto
	protoc --go_out=apps/todo-service/gen/todopb \
	       --go_opt=paths=source_relative \
	       --go-grpc_out=apps/todo-service/gen/todopb \
	       --go-grpc_opt=paths=source_relative \
	       -I api/v1 \
	       api/v1/todo.proto

gen-proto-java:
	@echo "Generating Java code from Protobuf..."
	@echo "Note: Java code generation is typically handled by Maven/Gradle plugins."
	@echo "If you need to generate manually, ensure protoc-gen-grpc-java is installed."
	@mkdir -p apps/hello-service/src/main/java-gen
	@if command -v protoc-gen-grpc-java >/dev/null 2>&1; then \
		protoc --java_out=apps/hello-service/src/main/java-gen \
		       --grpc-java_out=apps/hello-service/src/main/java-gen \
		       -I api/v1 \
		       api/v1/hello.proto; \
	else \
		echo "Warning: protoc-gen-grpc-java not found. Java code will be generated by Maven/Gradle."; \
		echo "To install: Download from https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/"; \
	fi

gen-proto-ts:
	@echo "Generating TypeScript code from Protobuf..."
	@if [ -d "apps/web" ]; then \
		cd apps/web && npm run gen-proto; \
	else \
		echo "Warning: apps/web directory not found. Skipping TypeScript generation."; \
		echo "TypeScript code will be generated when the web app is initialized."; \
	fi

# CI verification
verify-proto:
	@echo "Verifying generated code is up to date..."
	@$(MAKE) proto
	@git diff --exit-code apps/*/gen apps/*/src/main/java-gen apps/*/src/gen || \
	  (echo "Generated code is out of date. Run 'make proto' and commit changes." && exit 1)

# App management targets (new unified interface)
list-apps:
	@./scripts/app-manager.sh list

create:
	@echo "Create a new app from template"
	@echo ""
	@read -p "App type (java/go/node): " app_type; \
	read -p "App name (e.g., user-service): " app_name; \
	read -p "Port (default: auto-assign): " port; \
	read -p "Description: " description; \
	if [ "$$app_type" = "java" ]; then \
		read -p "Java package (default: com.pingxin403.cuckoo.$$app_name): " package; \
	fi; \
	if [ "$$app_type" = "go" ]; then \
		read -p "Go module (default: github.com/pingxin403/cuckoo/apps/$$app_name): " module; \
	fi; \
	read -p "Team name (default: platform-team): " team; \
	cmd="./scripts/create-app.sh $$app_type $$app_name"; \
	[ -n "$$port" ] && cmd="$$cmd --port $$port"; \
	[ -n "$$description" ] && cmd="$$cmd --description \"$$description\""; \
	[ -n "$$package" ] && cmd="$$cmd --package $$package"; \
	[ -n "$$module" ] && cmd="$$cmd --module $$module"; \
	[ -n "$$team" ] && cmd="$$cmd --team $$team"; \
	eval $$cmd

build:
ifdef APP
	@./scripts/app-manager.sh build $(APP)
else
	@./scripts/app-manager.sh build
endif

test:
ifdef APP
	@./scripts/app-manager.sh test $(APP)
else
	@./scripts/app-manager.sh test
endif

lint:
ifdef APP
	@./scripts/app-manager.sh lint $(APP)
else
	@./scripts/app-manager.sh lint
endif

lint-fix:
ifdef APP
	@./scripts/app-manager.sh lint-fix $(APP)
else
	@./scripts/app-manager.sh lint-fix
endif

format:
ifdef APP
	@./scripts/app-manager.sh format $(APP)
else
	@./scripts/app-manager.sh format
endif

docker-build:
ifdef APP
	@./scripts/app-manager.sh docker $(APP)
else
	@./scripts/app-manager.sh docker
endif

run:
ifdef APP
	@./scripts/app-manager.sh run $(APP)
else
	@echo "Error: APP parameter required for run command"
	@echo "Usage: make run APP=<app-name>"
	@echo "Available apps:"
	@./scripts/app-manager.sh list
	@exit 1
endif

clean:
ifdef APP
	@./scripts/app-manager.sh clean $(APP)
else
	@./scripts/app-manager.sh clean
endif

# Test coverage targets
test-coverage: test-coverage-hello test-coverage-todo

test-coverage-hello:
	@echo "Running Hello service tests with coverage..."
	@cd apps/hello-service && ./mvnw test jacoco:report
	@echo "Coverage report: apps/hello-service/build/reports/jacoco/test/html/index.html"

test-coverage-todo:
	@echo "Running TODO service tests with coverage..."
	@cd apps/todo-service && ./scripts/test-coverage.sh

# Verify coverage thresholds (for CI)
verify-coverage: verify-coverage-hello verify-coverage-todo

verify-coverage-hello:
	@echo "Verifying Hello service coverage..."
	@cd apps/hello-service && ./mvnw test jacoco:check

verify-coverage-todo:
	@echo "Verifying TODO service coverage..."
	@cd apps/todo-service && ./scripts/test-coverage.sh

# Development mode
dev:
	@echo "Starting all services in development mode..."
	@./scripts/dev.sh

# Pre-commit checks (run all quality checks before commit)
pre-commit:
	@echo "Running pre-commit checks..."
	@./scripts/pre-commit-checks.sh
