# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - unused        # Check for unused code
    - misspell      # Check for misspelled words
    - gosec         # Security checks
    - gocyclo       # Cyclomatic complexity
    - unconvert     # Remove unnecessary type conversions
  disable:
    - staticcheck   # Disabled due to false positives in test code

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
        disabled: false
      - name: blank-imports
        severity: warning
        disabled: false
      - name: context-as-argument
        severity: warning
        disabled: false
      - name: dot-imports
        severity: warning
        disabled: false
      - name: error-return
        severity: warning
        disabled: false
      - name: error-strings
        severity: warning
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false
      - name: if-return
        severity: warning
        disabled: false
      - name: increment-decrement
        severity: warning
        disabled: false
      - name: var-declaration
        severity: warning
        disabled: false
      - name: range
        severity: warning
        disabled: false
      - name: receiver-naming
        severity: warning
        disabled: false
      - name: time-naming
        severity: warning
        disabled: false
      - name: unexported-return
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
        disabled: false
      - name: errorf
        severity: warning
        disabled: false

  gosec:
    excludes:
      - G104 # Audit errors not checked (covered by errcheck)
      - G402 # TLS InsecureSkipVerify (acceptable for local development)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go$
      linters:
        - gocyclo
        - errcheck
        - gosec
        - staticcheck  # Allow some flexibility in test code

    # Exclude generated protobuf code
    - path: gen/
      linters:
        - all
    
    # Exclude client code from some checks
    - path: client/
      linters:
        - staticcheck  # Allow deprecated grpc.Dial in client code

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
