#!/bin/bash

# Centralized Proto Generator Script
# Generates protobuf code for all languages to api/gen directory
# Usage: ./scripts/proto-generator-new.sh [language]
#
# Languages: go, java, typescript, ts, all (default)

set -e

LANGUAGE="${1:-all}"
API_GEN_DIR="api/gen"
PROTO_DIR="api/v1"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Check if required tools are installed
check_prerequisites() {
    local missing_tools=""
    
    if ! command -v protoc >/dev/null 2>&1; then
        missing_tools="$missing_tools protoc"
    fi
    
    if [ "$LANGUAGE" = "go" ] || [ "$LANGUAGE" = "all" ]; then
        if ! command -v protoc-gen-go >/dev/null 2>&1; then
            missing_tools="$missing_tools protoc-gen-go"
        fi
        if ! command -v protoc-gen-go-grpc >/dev/null 2>&1; then
            missing_tools="$missing_tools protoc-gen-go-grpc"
        fi
    fi
    
    if [ -n "$missing_tools" ]; then
        log_error "Missing required tools:$missing_tools"
        log_error "Please install them before running this script"
        return 1
    fi
    
    return 0
}

# Generate Go code for a proto file
generate_go() {
    local proto_file=$1
    local proto_name=$(basename "$proto_file" .proto)
    
    # Map proto file names to package directory names
    local output_subdir
    case "$proto_name" in
        im-gateway)
            output_subdir="im-gatewaypb"
            ;;
        shortener)
            output_subdir="shortenerpb"
            ;;
        *)
            output_subdir="${proto_name}pb"
            ;;
    esac
    
    local output_dir="$API_GEN_DIR/go/$output_subdir"
    
    log_info "  [Go] Generating from $proto_file -> $output_dir"
    
    mkdir -p "$output_dir"
    
    if protoc \
        --go_out="$output_dir" \
        --go_opt=paths=source_relative \
        --go-grpc_out="$output_dir" \
        --go-grpc_opt=paths=source_relative \
        -I "$PROTO_DIR" \
        "$proto_file"; then
        
        # Verify generated files exist
        if [ -f "$output_dir/${proto_name}.pb.go" ] && [ -f "$output_dir/${proto_name}_grpc.pb.go" ]; then
            log_success "  [Go] Generated ${proto_name}.pb.go and ${proto_name}_grpc.pb.go"
            return 0
        else
            log_error "  [Go] Generated files not found"
            return 1
        fi
    else
        log_error "  [Go] Generation failed for $proto_file"
        return 1
    fi
}

# Generate Java code for a proto file
generate_java() {
    local proto_file=$1
    local proto_name=$(basename "$proto_file" .proto)
    local output_dir="$API_GEN_DIR/java"
    
    log_info "  [Java] Generating from $proto_file -> $output_dir"
    
    mkdir -p "$output_dir"
    
    # Check if protoc-gen-grpc-java is available
    if ! command -v protoc-gen-grpc-java >/dev/null 2>&1; then
        log_warning "  [Java] protoc-gen-grpc-java not found, skipping"
        log_warning "  [Java] Java code should be generated by Maven/Gradle plugins"
        return 0
    fi
    
    if protoc \
        --java_out="$output_dir" \
        --grpc-java_out="$output_dir" \
        -I "$PROTO_DIR" \
        "$proto_file"; then
        
        log_success "  [Java] Generated code for $proto_name"
        return 0
    else
        log_error "  [Java] Generation failed for $proto_file"
        return 1
    fi
}

# Generate TypeScript code for a proto file
generate_typescript() {
    local proto_file=$1
    local proto_name=$(basename "$proto_file" .proto)
    
    # Map proto file names to package directory names
    local output_subdir
    case "$proto_name" in
        im-gateway)
            output_subdir="im-gatewaypb"
            ;;
        shortener)
            output_subdir="shortenerpb"
            ;;
        *)
            output_subdir="${proto_name}pb"
            ;;
    esac
    
    local output_dir="$API_GEN_DIR/typescript/$output_subdir"
    
    log_info "  [TypeScript] Generating from $proto_file -> $output_dir"
    
    mkdir -p "$output_dir"
    
    # Check if ts-proto plugin is available
    if [ ! -f "node_modules/.bin/protoc-gen-ts_proto" ]; then
        log_warning "  [TypeScript] protoc-gen-ts_proto not found"
        log_warning "  [TypeScript] Please run: npm install ts-proto"
        return 0
    fi
    
    if protoc \
        --plugin=./node_modules/.bin/protoc-gen-ts_proto \
        --ts_proto_out="$output_dir" \
        --ts_proto_opt=esModuleInterop=true \
        -I "$PROTO_DIR" \
        "$proto_file"; then
        
        log_success "  [TypeScript] Generated code for $proto_name"
        return 0
    else
        log_error "  [TypeScript] Generation failed for $proto_file"
        return 1
    fi
}

# Process all proto files
process_proto_files() {
    local lang=$1
    local proto_files=$(find "$PROTO_DIR" -name "*.proto" -type f)
    local total_files=$(echo "$proto_files" | wc -l)
    local current=0
    local failed_files=""
    
    if [ -z "$proto_files" ]; then
        log_warning "No proto files found in $PROTO_DIR"
        return 0
    fi
    
    log_info "Found $total_files proto files to process"
    echo ""
    
    for proto_file in $proto_files; do
        current=$((current + 1))
        local proto_name=$(basename "$proto_file")
        
        log_info "[$current/$total_files] Processing $proto_name"
        
        case $lang in
            go)
                if ! generate_go "$proto_file"; then
                    failed_files="$failed_files $proto_name"
                fi
                ;;
            java)
                if ! generate_java "$proto_file"; then
                    failed_files="$failed_files $proto_name"
                fi
                ;;
            typescript|ts)
                if ! generate_typescript "$proto_file"; then
                    failed_files="$failed_files $proto_name"
                fi
                ;;
            all)
                local file_failed=false
                if ! generate_go "$proto_file"; then
                    file_failed=true
                fi
                if ! generate_java "$proto_file"; then
                    file_failed=true
                fi
                if ! generate_typescript "$proto_file"; then
                    file_failed=true
                fi
                if [ "$file_failed" = true ]; then
                    failed_files="$failed_files $proto_name"
                fi
                ;;
            *)
                log_error "Unknown language: $lang"
                return 1
                ;;
        esac
        
        echo ""
    done
    
    if [ -n "$failed_files" ]; then
        log_error "Failed to generate code for:$failed_files"
        return 1
    fi
    
    return 0
}

# Update Go module dependencies
update_go_module() {
    if [ -f "$API_GEN_DIR/go/go.mod" ]; then
        log_info "Updating Go module dependencies..."
        (cd "$API_GEN_DIR/go" && go mod tidy) || {
            log_warning "Failed to run go mod tidy, but continuing..."
        }
    fi
}

# Main execution
main() {
    local start_time=$(date +%s)
    
    log_info "========================================="
    log_info "Centralized Proto Code Generation"
    log_info "========================================="
    log_info "Language: $LANGUAGE"
    log_info "Output directory: $API_GEN_DIR"
    log_info "Proto directory: $PROTO_DIR"
    echo ""
    
    # Check prerequisites
    if ! check_prerequisites; then
        exit 1
    fi
    
    # Process proto files
    if ! process_proto_files "$LANGUAGE"; then
        log_error "Proto generation failed!"
        exit 1
    fi
    
    # Update Go module if generating Go code
    if [ "$LANGUAGE" = "go" ] || [ "$LANGUAGE" = "all" ]; then
        update_go_module
    fi
    
    local end_time=$(date +%s)
    local duration=$((end_time - start_time))
    
    echo ""
    log_info "========================================="
    log_success "✓ Proto generation completed successfully!"
    log_info "Duration: ${duration}s"
    log_info "========================================="
}

main
